# Generated by Django 6.0.6 on 2026-06-29 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('properties', '0002_propertyimage_verification_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING_SIGNATURE', 'Pending Signature'), ('ACTIVE', 'Active'), ('EXPIRING_SOON', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], db_index=True, default='PENDING_SIGNATURE', max_length=20)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('rent_due_day', models.PositiveSmallIntegerField(default=1, help_text='Day of month rent is due')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('duration_months', models.PositiveSmallIntegerField(default=12)),
                ('furnished', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('signed_pdf', models.FileField(blank=True, upload_to='leases/signed/')),
                ('tenant_signed_at', models.DateTimeField(blank=True, null=True)),
                ('landlord_signed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lease', to='applications.rentalapplication')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases_as_landlord', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases_as_tenant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('LEASE_AGREEMENT', 'Lease Agreement'), ('ADDENDUM', 'Addendum'), ('SERVICE_CONTRACT', 'Service Contract'), ('SIGNED_COPY', 'Signed Copy')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='leases/documents/')),
                ('is_shareable', models.BooleanField(default=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leases.lease')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_lease_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseAddendum',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('effective_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_addendums', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addendums', to='leases.lease')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addendum', to='leases.leasedocument')),
            ],
            options={
                'verbose_name_plural': 'lease addenda',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signer_role', models.CharField(choices=[('TENANT', 'Tenant'), ('LANDLORD', 'Landlord')], max_length=10)),
                ('signature_method', models.CharField(choices=[('ELECTRONIC', 'Electronic'), ('UPLOAD', 'Uploaded PDF')], default='ELECTRONIC', max_length=20)),
                ('signed_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_signatures', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='leases.lease')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='leases.leasedocument')),
            ],
            options={
                'ordering': ['signed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['status', '-created_at'], name='leases_leas_status_52ed0b_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['tenant', 'status'], name='leases_leas_tenant__9c2189_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['landlord', 'status'], name='leases_leas_landlor_145517_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['end_date'], name='leases_leas_end_dat_3ab4df_idx'),
        ),
        migrations.AddConstraint(
            model_name='digitalsignature',
            constraint=models.UniqueConstraint(fields=('lease', 'signer_role'), name='unique_lease_signer_role'),
        ),
    ]
