# Generated by Django 6.0.6 on 2026-06-29 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_propertyimage_verification_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('AWAITING_DOCS', 'Awaiting Documents'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], db_index=True, default='PENDING', max_length=20)),
                ('stage', models.CharField(choices=[('DOCUMENT_REVIEW', 'Document Review'), ('ON_SITE_INSPECTION', 'On-site Inspection'), ('SAFETY_SCORING', 'Safety Scoring'), ('FINAL_REVIEW', 'Final Review')], default='DOCUMENT_REVIEW', max_length=30)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('inspector_notes', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('changes_requested', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_verifications', to=settings.AUTH_USER_MODEL)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_case', to='properties.property')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('notes', models.TextField(blank=True, default='')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_score_record', to='properties.property')),
                ('scored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_scores_given', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_scores', to='verification.verificationcase')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_audit_logs', to='properties.property')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='verification.verificationcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('TITLE_DEED', 'Title Deed'), ('TAX_INFO', 'Tax Information'), ('CONTRACT', 'Contract'), ('ID_PASSPORT', 'ID / Passport'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(blank=True, upload_to='verification/documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='verification.verificationcase')),
                ('property_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_links', to='properties.propertydocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doc_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('SAFETY', 'Safety'), ('UTILITIES', 'Utilities'), ('NOISE', 'Noise'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reports', to='properties.property')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'status'], name='verificatio_propert_5bd6ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='SafetyScoreFactor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor_type', models.CharField(choices=[('NEIGHBORHOOD', 'Neighborhood Safety'), ('BUILDING_CONDITION', 'Building Condition'), ('ACCESS_CONTROL', 'Access Control'), ('LIGHTING', 'Lighting'), ('EMERGENCY_READINESS', 'Emergency Readiness')], max_length=30)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_score', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('safety_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='verification.safetyscore')),
            ],
            options={
                'ordering': ['factor_type'],
                'unique_together': {('safety_score', 'factor_type')},
            },
        ),
        migrations.AddIndex(
            model_name='verificationcase',
            index=models.Index(fields=['status', '-submitted_at'], name='verificatio_status_f563a1_idx'),
        ),
    ]
