# Generated by Django 6.0.6 on 2026-06-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified_landlord',
            field=models.BooleanField(default=False),
        ),
    ]
