# Generated by Django 6.0.6 on 2026-06-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_verified_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_payment_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_system_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
