# Generated by Django 6.0.6 on 2026-06-29 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='DRAFT', max_length=20)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('cover_letter', models.TextField(blank=True, default='')),
                ('employment_title', models.CharField(blank=True, default='', max_length=255)),
                ('employer', models.CharField(blank=True, default='', max_length=255)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('screening_score', models.PositiveSmallIntegerField(default=0)),
                ('screening_label', models.CharField(blank=True, default='', max_length=100)),
                ('income_rent_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('landlord_notes', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationReference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='applications.rentalapplication')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SUBMITTED', 'Submitted'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('NOTE', 'Note')], max_length=30)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_events', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.rentalapplication')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('document', models.FileField(upload_to='applications/documents/')),
                ('doc_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PAYSLIP', 'Payslip'), ('BANK_STATEMENT', 'Bank Statement'), ('EMPLOYMENT_LETTER', 'Employment Letter'), ('REFERENCE_LETTER', 'Reference Letter'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.rentalapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rentalapplication',
            index=models.Index(fields=['status', '-created_at'], name='application_status_1ee2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalapplication',
            index=models.Index(fields=['tenant', 'status'], name='application_tenant__9a42d2_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalapplication',
            index=models.Index(fields=['-screening_score'], name='application_screeni_85d2b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentalapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED'])), fields=('tenant', 'property'), name='unique_active_application_per_tenant_property'),
        ),
    ]
