# Generated by Django 6.0.6 on 2026-06-29 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('due_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='leases.lease')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='LandlordSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium')], default='FREE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa')], default='MPESA', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('mpesa_merchant_request_id', models.CharField(blank=True, default='', max_length=64)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('mpesa_transaction_date', models.CharField(blank=True, default='', max_length=32)),
                ('mpesa_result_code', models.CharField(blank=True, default='', max_length=10)),
                ('mpesa_result_desc', models.CharField(blank=True, default='', max_length=255)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_callback', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.invoice')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('receipt_file', models.FileField(blank=True, upload_to='payments/receipts/')),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('MPESA_PHONE', 'M-Pesa Phone'), ('PAYBILL', 'Paybill'), ('TILL', 'Till Number')], max_length=20)),
                ('account_label', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['lease', 'status'], name='payments_in_lease_i_72ac31_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date', 'status'], name='payments_in_due_dat_745dd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('lease', 'billing_period_start', 'billing_period_end'), name='unique_lease_billing_period'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'status'], name='payments_pa_tenant__3ffcb1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['landlord', 'status'], name='payments_pa_landlor_ebd781_idx'),
        ),
    ]
